version: '2.19'

services:
  postgres:
    container_name: eds-postgres
    image: postgres:15.3
    restart: on-failure
    environment:
      - POSTGRES_USER=${PGUSER}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE}
    ports:
      - ${PGPORT}:${PGPORT}
    networks:
      - eds-net

networks:
  eds-net: { }