name: eg_dart_shelf
description: A server app using the shelf package and Docker.
version: 1.0.0
repository: https://github.com/gusriil/eg-dart-shelf

environment:
  sdk: ^3.0.5

dependencies:
  args: ^2.4.2
  corsac_jwt: ^1.0.0-nullsafety.1
  dotenv: ^4.1.0
  email_validator: ^2.1.17
  postgres_pool: ^2.1.6
  shelf: ^1.4.0
  shelf_cors_headers: ^0.1.5
  shelf_router: ^1.1.4
  slugify: ^2.0.0

dev_dependencies:
  faker: ^2.1.0
  http: ^1.1.0
  lints: ^2.1.1
  test: ^1.24.4
  test_process: ^2.1.0
