version: '2'

services:
  simple-kotlin-restful-api:
    container_name: simple-kotlin-restful-api
    image: simple-kotlin-restful-api:0.0.1
    ports:
      - 8080:8080
    environment:
      DATABASE_USERNAME: kotlin
      DATABASE_PASSWORD: kotlin
      DATABASE_URL: jdbc:postgresql://simple-kotlin-restful-api-postgres:5432/restful-api
  simple-kotlin-restful-api-postgres:
    container_name: "simple-kotlin-restful-api-postgres"
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kotlin
      POSTGRES_USER: kotlin
      POSTGRES_DB: restful-api