// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package com.gusrylmubarok.ecommerce.grpc.grpc.v1;

public final class PaymentGatewayService {
  private PaymentGatewayService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_BillingDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_BillingDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_Card_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_Card_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_StripeAccount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_StripeAccount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_PaymentMethodDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_PaymentMethodDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_Refund_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_Refund_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_AchCreditTransfer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_AchCreditTransfer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_Owner_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_Owner_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_Receiver_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_Receiver_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_CreateSourceReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_CreateSourceReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_CreateSourceReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_CreateSourceReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_UpdateSourceReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_UpdateSourceReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_UpdateSourceReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_UpdateSourceReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_SourceId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_SourceId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_SourceId_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_SourceId_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_Source_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_Source_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_CreateChargeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_CreateChargeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_CreateChargeReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_CreateChargeReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_UpdateChargeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_UpdateChargeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_UpdateChargeReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_UpdateChargeReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_CaptureChargeReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_CaptureChargeReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_CaptureChargeReq_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_CaptureChargeReq_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_ChargeId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_ChargeId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_ChargeId_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_ChargeId_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_CustomerId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_CustomerId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_CustomerId_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_CustomerId_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gusrylmubarok_v1_Charge_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gusrylmubarok_v1_Charge_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033PaymentGatewayService.proto\022\024com.gusry" +
      "lmubarok.v1\032\037google/protobuf/timestamp.p" +
      "roto\"\212\001\n\007Address\022\n\n\002id\030\001 \001(\t\022\016\n\006number\030\002" +
      " \001(\t\022\021\n\tresidency\030\003 \001(\t\022\016\n\006street\030\004 \001(\t\022" +
      "\014\n\004city\030\005 \001(\t\022\r\n\005state\030\006 \001(\t\022\017\n\007country\030" +
      "\007 \001(\t\022\022\n\npostalCode\030\010 \001(\t\"l\n\016BillingDeta" +
      "ils\022.\n\007address\030\001 \001(\0132\035.com.gusrylmubarok" +
      ".v1.Address\022\r\n\005email\030\002 \001(\t\022\014\n\004name\030\003 \001(\t" +
      "\022\r\n\005phone\030\004 \001(\t\"\360\001\n\004Card\022\n\n\002id\030\001 \001(\t\022\014\n\004" +
      "name\030\002 \001(\t\022.\n\007address\030\003 \001(\0132\035.com.gusryl" +
      "mubarok.v1.Address\022\r\n\005brand\030\004 \001(\t\022\017\n\007cou" +
      "ntry\030\005 \001(\t\022\020\n\010expMonth\030\006 \001(\r\022\017\n\007expYear\030" +
      "\007 \001(\r\022\023\n\013fingerprint\030\010 \001(\t\022\017\n\007funding\030\t " +
      "\001(\t\022\024\n\014installments\030\n \001(\r\022\r\n\005last4\030\013 \001(\t" +
      "\022\020\n\010customer\030\014 \001(\t\"\033\n\rStripeAccount\022\n\n\002i" +
      "d\030\001 \001(\t\"\212\001\n\024PaymentMethodDetails\022(\n\004card" +
      "\030\001 \001(\0132\032.com.gusrylmubarok.v1.Card\022\014\n\004ty" +
      "pe\030\002 \001(\t\022:\n\rstripeAccount\030\003 \001(\0132#.com.gu" +
      "srylmubarok.v1.StripeAccount\"p\n\006Refund\022\n" +
      "\n\002id\030\001 \001(\t\022\016\n\006amount\030\002 \001(\r\022\013\n\003fee\030\003 \001(\t\022" +
      "+\n\007created\030\004 \001(\0132\032.google.protobuf.Times" +
      "tamp\022\020\n\010currency\030\005 \001(\t\"{\n\021AchCreditTrans" +
      "fer\022\025\n\raccountNumber\030\001 \001(\t\022\025\n\rroutingNum" +
      "ber\030\002 \001(\t\022\023\n\013fingerprint\030\003 \001(\t\022\020\n\010bankNa" +
      "me\030\004 \001(\t\022\021\n\tswiftCode\030\005 \001(\t\"\337\001\n\005Owner\022.\n" +
      "\007address\030\001 \001(\0132\035.com.gusrylmubarok.v1.Ad" +
      "dress\022\r\n\005email\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\r\n\005ph" +
      "one\030\004 \001(\t\0226\n\017verifiedAddress\030\005 \001(\0132\035.com" +
      ".gusrylmubarok.v1.Address\022\025\n\rverifiedEma" +
      "il\030\006 \001(\t\022\024\n\014verifiedName\030\007 \001(\t\022\025\n\rverifi" +
      "edPhone\030\010 \001(\t\"\216\003\n\010Receiver\022\017\n\007address\030\001 " +
      "\001(\t\022\025\n\ramountCharged\030\002 \001(\r\022\026\n\016amountRece" +
      "ived\030\003 \001(\r\022\026\n\016amountReturned\030\004 \001(\r\022U\n\026re" +
      "fundAttributesMethod\030\005 \001(\01625.com.gusrylm" +
      "ubarok.v1.Receiver.RefundAttributesMetho" +
      "d\022T\n\026refundAttributesStatus\030\006 \001(\01624.com." +
      "gusrylmubarok.v1.Receiver.RefundAttribut" +
      "eStatus\"9\n\026RefundAttributesMethod\022\t\n\005EMA" +
      "IL\020\000\022\n\n\006MANUAL\020\001\022\010\n\004NONE\020\002\"B\n\025RefundAttr" +
      "ibuteStatus\022\013\n\007MISSING\020\000\022\r\n\tREQUESTED\020\001\022" +
      "\r\n\tAVAILABLE\020\002\"\314\002\n\017CreateSourceReq\022\014\n\004ty" +
      "pe\030\001 \001(\t\022\016\n\006amount\030\002 \001(\r\022\020\n\010currency\030\003 \001" +
      "(\t\022*\n\005owner\030\004 \001(\0132\033.com.gusrylmubarok.v1" +
      ".Owner\022\033\n\023statementDescriptor\030\005 \001(\t\022(\n\004f" +
      "low\030\006 \001(\0162\032.com.gusrylmubarok.v1.Flow\0220\n" +
      "\010receiver\030\007 \001(\0132\036.com.gusrylmubarok.v1.R" +
      "eceiver\022*\n\005usage\030\010 \001(\0162\033.com.gusrylmubar" +
      "ok.v1.Usage\0328\n\010Response\022,\n\006source\030\001 \001(\0132" +
      "\034.com.gusrylmubarok.v1.Source\"\231\001\n\017Update" +
      "SourceReq\022\020\n\010sourceId\030\001 \001(\t\022\016\n\006amount\030\002 " +
      "\001(\r\022*\n\005owner\030\003 \001(\0132\033.com.gusrylmubarok.v" +
      "1.Owner\0328\n\010Response\022,\n\006source\030\001 \001(\0132\034.co" +
      "m.gusrylmubarok.v1.Source\"P\n\010SourceId\022\n\n" +
      "\002id\030\001 \001(\t\0328\n\010Response\022,\n\006source\030\001 \001(\0132\034." +
      "com.gusrylmubarok.v1.Source\"s\n\021AttachOrD" +
      "etachReq\022\020\n\010sourceId\030\001 \001(\t\022\022\n\ncustomerId" +
      "\030\002 \001(\t\0328\n\010Response\022,\n\006source\030\001 \001(\0132\034.com" +
      ".gusrylmubarok.v1.Source\"\301\003\n\006Source\022\n\n\002i" +
      "d\030\001 \001(\t\022\016\n\006amount\030\002 \001(\r\022\024\n\014clientSecret\030" +
      "\003 \001(\t\022\017\n\007created\030\004 \001(\004\022\020\n\010currency\030\005 \001(\t" +
      "\022(\n\004flow\030\006 \001(\0162\032.com.gusrylmubarok.v1.Fl" +
      "ow\022*\n\005owner\030\007 \001(\0132\033.com.gusrylmubarok.v1" +
      ".Owner\0220\n\010receiver\030\010 \001(\0132\036.com.gusrylmub" +
      "arok.v1.Receiver\022\033\n\023statementDescriptor\030" +
      "\t \001(\t\0223\n\006status\030\n \001(\0162#.com.gusrylmubaro" +
      "k.v1.Source.Status\022\014\n\004type\030\013 \001(\t\022*\n\005usag" +
      "e\030\014 \001(\0162\033.com.gusrylmubarok.v1.Usage\"N\n\006" +
      "Status\022\r\n\tCANCELLED\020\000\022\016\n\nCHARGEABLE\020\001\022\014\n" +
      "\010CONSUMED\020\002\022\n\n\006FAILED\020\003\022\013\n\007PENDING\020\004\"\333\001\n" +
      "\017CreateChargeReq\022\016\n\006amount\030\001 \001(\r\022\020\n\010curr" +
      "ency\030\002 \001(\t\022\022\n\ncustomerId\030\003 \001(\t\022\023\n\013descri" +
      "ption\030\004 \001(\t\022\024\n\014receiptEmail\030\005 \001(\t\022\020\n\010sou" +
      "rceId\030\006 \001(\t\022\033\n\023statementDescriptor\030\007 \001(\t" +
      "\0328\n\010Response\022,\n\006charge\030\001 \001(\0132\034.com.gusry" +
      "lmubarok.v1.Charge\"\234\001\n\017UpdateChargeReq\022\020" +
      "\n\010chargeId\030\001 \001(\t\022\022\n\ncustomerId\030\002 \001(\t\022\023\n\013" +
      "description\030\003 \001(\t\022\024\n\014receiptEmail\030\004 \001(\t\032" +
      "8\n\010Response\022,\n\006charge\030\001 \001(\0132\034.com.gusryl" +
      "mubarok.v1.Charge\"\241\001\n\020CaptureChargeReq\022\020" +
      "\n\010chargeId\030\001 \001(\t\022\016\n\006amount\030\002 \001(\r\022\024\n\014rece" +
      "iptEmail\030\003 \001(\t\022\033\n\023statementDescriptor\030\004 " +
      "\001(\t\0328\n\010Response\022,\n\006charge\030\001 \001(\0132\034.com.gu" +
      "srylmubarok.v1.Charge\"P\n\010ChargeId\022\n\n\002id\030" +
      "\001 \001(\t\0328\n\010Response\022,\n\006charge\030\001 \001(\0132\034.com." +
      "gusrylmubarok.v1.Charge\"R\n\nCustomerId\022\n\n" +
      "\002id\030\001 \001(\t\0328\n\010Response\022,\n\006charge\030\001 \003(\0132\034." +
      "com.gusrylmubarok.v1.Charge\"\215\006\n\006Charge\022\n" +
      "\n\002id\030\001 \001(\t\022\016\n\006amount\030\002 \001(\r\022\026\n\016amountCapt" +
      "ured\030\003 \001(\r\022\026\n\016amountRefunded\030\004 \001(\r\022\034\n\024ba" +
      "lanceTransactionId\030\005 \001(\t\022<\n\016billingDetai" +
      "ls\030\006 \001(\0132$.com.gusrylmubarok.v1.BillingD" +
      "etails\022%\n\035calculatedStatementDescriptor\030" +
      "\007 \001(\t\022\020\n\010captured\030\010 \001(\010\022\017\n\007created\030\t \001(\004" +
      "\022\020\n\010currency\030\n \001(\t\022\022\n\ncustomerId\030\013 \001(\t\022\023" +
      "\n\013description\030\014 \001(\t\022\020\n\010disputed\030\r \001(\010\022\023\n" +
      "\013failureCode\030\016 \001(\r\022\026\n\016failureMessage\030\017 \001" +
      "(\t\022\021\n\tinvoiceId\030\020 \001(\t\022\017\n\007orderId\030\021 \001(\t\022\014" +
      "\n\004paid\030\022 \001(\010\022\027\n\017paymentMethodId\030\023 \001(\t\022H\n" +
      "\024paymentMethodDetails\030\024 \001(\0132*.com.gusryl" +
      "mubarok.v1.PaymentMethodDetails\022\024\n\014recei" +
      "ptEmail\030\025 \001(\t\022\025\n\rreceiptNumber\030\026 \001(\t\022\020\n\010" +
      "refunded\030\027 \001(\010\022-\n\007refunds\030\030 \003(\0132\034.com.gu" +
      "srylmubarok.v1.Refund\022\033\n\023statementDescri" +
      "ptor\030\031 \001(\t\0223\n\006status\030\032 \001(\0162#.com.gusrylm" +
      "ubarok.v1.Charge.Status\022\020\n\010sourceId\030\033 \001(" +
      "\t\"0\n\006Status\022\r\n\tSUCCEEDED\020\000\022\013\n\007PENDING\020\001\022" +
      "\n\n\006FAILED\020\002*B\n\004Flow\022\014\n\010REDIRECT\020\000\022\014\n\010REC" +
      "EIVER\020\001\022\024\n\020CODEVERIFICATION\020\002\022\010\n\004NONE\020\003*" +
      "$\n\005Usage\022\014\n\010REUSABLE\020\000\022\r\n\tSINGLEUSE\020\0012\346\003" +
      "\n\rChargeService\022_\n\006Create\022%.com.gusrylmu" +
      "barok.v1.CreateChargeReq\032..com.gusrylmub" +
      "arok.v1.CreateChargeReq.Response\022S\n\010Retr" +
      "ieve\022\036.com.gusrylmubarok.v1.ChargeId\032\'.c" +
      "om.gusrylmubarok.v1.ChargeId.Response\022_\n" +
      "\006Update\022%.com.gusrylmubarok.v1.UpdateCha" +
      "rgeReq\032..com.gusrylmubarok.v1.UpdateChar" +
      "geReq.Response\022b\n\007Capture\022&.com.gusrylmu" +
      "barok.v1.CaptureChargeReq\032/.com.gusrylmu" +
      "barok.v1.CaptureChargeReq.Response\022Z\n\013Re" +
      "trieveAll\022 .com.gusrylmubarok.v1.Custome" +
      "rId\032).com.gusrylmubarok.v1.CustomerId.Re" +
      "sponse2\360\003\n\rSourceService\022_\n\006Create\022%.com" +
      ".gusrylmubarok.v1.CreateSourceReq\032..com." +
      "gusrylmubarok.v1.CreateSourceReq.Respons" +
      "e\022S\n\010Retrieve\022\036.com.gusrylmubarok.v1.Sou" +
      "rceId\032\'.com.gusrylmubarok.v1.SourceId.Re" +
      "sponse\022_\n\006Update\022%.com.gusrylmubarok.v1." +
      "UpdateSourceReq\032..com.gusrylmubarok.v1.U" +
      "pdateSourceReq.Response\022c\n\006Attach\022\'.com." +
      "gusrylmubarok.v1.AttachOrDetachReq\0320.com" +
      ".gusrylmubarok.v1.AttachOrDetachReq.Resp" +
      "onse\022c\n\006Detach\022\'.com.gusrylmubarok.v1.At" +
      "tachOrDetachReq\0320.com.gusrylmubarok.v1.A" +
      "ttachOrDetachReq.ResponseB,\n(com.gusrylm" +
      "ubarok.ecommerce.grpc.grpc.v1P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_gusrylmubarok_v1_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gusrylmubarok_v1_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_Address_descriptor,
        new java.lang.String[] { "Id", "Number", "Residency", "Street", "City", "State", "Country", "PostalCode", });
    internal_static_com_gusrylmubarok_v1_BillingDetails_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gusrylmubarok_v1_BillingDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_BillingDetails_descriptor,
        new java.lang.String[] { "Address", "Email", "Name", "Phone", });
    internal_static_com_gusrylmubarok_v1_Card_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_gusrylmubarok_v1_Card_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_Card_descriptor,
        new java.lang.String[] { "Id", "Name", "Address", "Brand", "Country", "ExpMonth", "ExpYear", "Fingerprint", "Funding", "Installments", "Last4", "Customer", });
    internal_static_com_gusrylmubarok_v1_StripeAccount_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_gusrylmubarok_v1_StripeAccount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_StripeAccount_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_gusrylmubarok_v1_PaymentMethodDetails_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_gusrylmubarok_v1_PaymentMethodDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_PaymentMethodDetails_descriptor,
        new java.lang.String[] { "Card", "Type", "StripeAccount", });
    internal_static_com_gusrylmubarok_v1_Refund_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_gusrylmubarok_v1_Refund_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_Refund_descriptor,
        new java.lang.String[] { "Id", "Amount", "Fee", "Created", "Currency", });
    internal_static_com_gusrylmubarok_v1_AchCreditTransfer_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_gusrylmubarok_v1_AchCreditTransfer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_AchCreditTransfer_descriptor,
        new java.lang.String[] { "AccountNumber", "RoutingNumber", "Fingerprint", "BankName", "SwiftCode", });
    internal_static_com_gusrylmubarok_v1_Owner_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_gusrylmubarok_v1_Owner_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_Owner_descriptor,
        new java.lang.String[] { "Address", "Email", "Name", "Phone", "VerifiedAddress", "VerifiedEmail", "VerifiedName", "VerifiedPhone", });
    internal_static_com_gusrylmubarok_v1_Receiver_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_com_gusrylmubarok_v1_Receiver_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_Receiver_descriptor,
        new java.lang.String[] { "Address", "AmountCharged", "AmountReceived", "AmountReturned", "RefundAttributesMethod", "RefundAttributesStatus", });
    internal_static_com_gusrylmubarok_v1_CreateSourceReq_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_com_gusrylmubarok_v1_CreateSourceReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_CreateSourceReq_descriptor,
        new java.lang.String[] { "Type", "Amount", "Currency", "Owner", "StatementDescriptor", "Flow", "Receiver", "Usage", });
    internal_static_com_gusrylmubarok_v1_CreateSourceReq_Response_descriptor =
      internal_static_com_gusrylmubarok_v1_CreateSourceReq_descriptor.getNestedTypes().get(0);
    internal_static_com_gusrylmubarok_v1_CreateSourceReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_CreateSourceReq_Response_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_com_gusrylmubarok_v1_UpdateSourceReq_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_com_gusrylmubarok_v1_UpdateSourceReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_UpdateSourceReq_descriptor,
        new java.lang.String[] { "SourceId", "Amount", "Owner", });
    internal_static_com_gusrylmubarok_v1_UpdateSourceReq_Response_descriptor =
      internal_static_com_gusrylmubarok_v1_UpdateSourceReq_descriptor.getNestedTypes().get(0);
    internal_static_com_gusrylmubarok_v1_UpdateSourceReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_UpdateSourceReq_Response_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_com_gusrylmubarok_v1_SourceId_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_com_gusrylmubarok_v1_SourceId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_SourceId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_gusrylmubarok_v1_SourceId_Response_descriptor =
      internal_static_com_gusrylmubarok_v1_SourceId_descriptor.getNestedTypes().get(0);
    internal_static_com_gusrylmubarok_v1_SourceId_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_SourceId_Response_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_descriptor,
        new java.lang.String[] { "SourceId", "CustomerId", });
    internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_Response_descriptor =
      internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_descriptor.getNestedTypes().get(0);
    internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_AttachOrDetachReq_Response_descriptor,
        new java.lang.String[] { "Source", });
    internal_static_com_gusrylmubarok_v1_Source_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_com_gusrylmubarok_v1_Source_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_Source_descriptor,
        new java.lang.String[] { "Id", "Amount", "ClientSecret", "Created", "Currency", "Flow", "Owner", "Receiver", "StatementDescriptor", "Status", "Type", "Usage", });
    internal_static_com_gusrylmubarok_v1_CreateChargeReq_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_com_gusrylmubarok_v1_CreateChargeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_CreateChargeReq_descriptor,
        new java.lang.String[] { "Amount", "Currency", "CustomerId", "Description", "ReceiptEmail", "SourceId", "StatementDescriptor", });
    internal_static_com_gusrylmubarok_v1_CreateChargeReq_Response_descriptor =
      internal_static_com_gusrylmubarok_v1_CreateChargeReq_descriptor.getNestedTypes().get(0);
    internal_static_com_gusrylmubarok_v1_CreateChargeReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_CreateChargeReq_Response_descriptor,
        new java.lang.String[] { "Charge", });
    internal_static_com_gusrylmubarok_v1_UpdateChargeReq_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_com_gusrylmubarok_v1_UpdateChargeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_UpdateChargeReq_descriptor,
        new java.lang.String[] { "ChargeId", "CustomerId", "Description", "ReceiptEmail", });
    internal_static_com_gusrylmubarok_v1_UpdateChargeReq_Response_descriptor =
      internal_static_com_gusrylmubarok_v1_UpdateChargeReq_descriptor.getNestedTypes().get(0);
    internal_static_com_gusrylmubarok_v1_UpdateChargeReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_UpdateChargeReq_Response_descriptor,
        new java.lang.String[] { "Charge", });
    internal_static_com_gusrylmubarok_v1_CaptureChargeReq_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_com_gusrylmubarok_v1_CaptureChargeReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_CaptureChargeReq_descriptor,
        new java.lang.String[] { "ChargeId", "Amount", "ReceiptEmail", "StatementDescriptor", });
    internal_static_com_gusrylmubarok_v1_CaptureChargeReq_Response_descriptor =
      internal_static_com_gusrylmubarok_v1_CaptureChargeReq_descriptor.getNestedTypes().get(0);
    internal_static_com_gusrylmubarok_v1_CaptureChargeReq_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_CaptureChargeReq_Response_descriptor,
        new java.lang.String[] { "Charge", });
    internal_static_com_gusrylmubarok_v1_ChargeId_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_com_gusrylmubarok_v1_ChargeId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_ChargeId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_gusrylmubarok_v1_ChargeId_Response_descriptor =
      internal_static_com_gusrylmubarok_v1_ChargeId_descriptor.getNestedTypes().get(0);
    internal_static_com_gusrylmubarok_v1_ChargeId_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_ChargeId_Response_descriptor,
        new java.lang.String[] { "Charge", });
    internal_static_com_gusrylmubarok_v1_CustomerId_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_com_gusrylmubarok_v1_CustomerId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_CustomerId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_gusrylmubarok_v1_CustomerId_Response_descriptor =
      internal_static_com_gusrylmubarok_v1_CustomerId_descriptor.getNestedTypes().get(0);
    internal_static_com_gusrylmubarok_v1_CustomerId_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_CustomerId_Response_descriptor,
        new java.lang.String[] { "Charge", });
    internal_static_com_gusrylmubarok_v1_Charge_descriptor =
      getDescriptor().getMessageTypes().get(19);
    internal_static_com_gusrylmubarok_v1_Charge_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gusrylmubarok_v1_Charge_descriptor,
        new java.lang.String[] { "Id", "Amount", "AmountCaptured", "AmountRefunded", "BalanceTransactionId", "BillingDetails", "CalculatedStatementDescriptor", "Captured", "Created", "Currency", "CustomerId", "Description", "Disputed", "FailureCode", "FailureMessage", "InvoiceId", "OrderId", "Paid", "PaymentMethodId", "PaymentMethodDetails", "ReceiptEmail", "ReceiptNumber", "Refunded", "Refunds", "StatementDescriptor", "Status", "SourceId", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
