// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PaymentGatewayService.proto

package com.gusrylmubarok.ecommerce.grpc.grpc.v1;

public interface SourceIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gusrylmubarok.v1.SourceId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * unique source ID from a source creation request
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * unique source ID from a source creation request
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
